version: 2.1

orbs:
  aws_assume_role: lbh-hackit/aws_assume_role@0.1.0

executors:
  docker-python:
    docker:
      - image: cimg/python:3.12
  docker-terraform:
    docker:
      - image: "hashicorp/terraform:light"

references:
  workspace_root: &workspace_root "~"
  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

commands:
  assume-role-and-persist-workspace:
    description: "Assumes deployment role and persists credentials across jobs"
    parameters:
      aws-account:
        type: string
    steps:
      - checkout
      - aws_assume_role/assume_role:
          account: <<parameters.aws-account>>
          profile_name: default
          role: "LBH_Circle_CI_Deployment_Role"
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - .aws
  # Init then Plan is used for "Preview" - don't add any "apply" steps
  terraform-init-then-plan:
    description: "Initializes and applies terraform configuration"
    parameters:
      environment:
        type: string
    steps:
      - *attach_workspace
      - checkout
      - run:
          command: |
            cd ./<<parameters.environment>>/
            terraform get -update=true
            terraform init
          name: get and init
      - run:
      # PLEASE LEAVE THIS AS A PLAN, IF YOU WANT TO CHANGE IT THEN SPEAK TO HUMAIRAA FIRST. 
          name: plan
          command: |
            cd ./<<parameters.environment>>/
            terraform plan
  # Used for actual deployment of Terraform resources.
  terraform-init-then-apply:
    description: "Initializes and applies terraform configuration"
    parameters:
      environment:
        type: string
    steps:
      - *attach_workspace
      - checkout
      - run:
          command: |
            cd ./<<parameters.environment>>/
            terraform get -update=true
            terraform init
          name: get and init
      - run:
          name: apply
          command: |
            cd ./<<parameters.environment>>/
            terraform apply -auto-approve

jobs:
  # Auth:
  assume-role-disaster-recovery:
    executor: docker-python
    steps:
      - assume-role-and-persist-workspace:
          aws-account: $AWS_ACCOUNT_DISASTER_RECOVERY
  preview-terraform-disaster-recovery-changes:
    executor: docker-terraform
    steps:
      - terraform-init-then-plan:
          environment: "disaster-recovery"
  # Infrastructure deployment:
  terraform-init-and-apply-to-disaster-recovery:
    executor: docker-terraform
    steps:
      - terraform-init-then-apply:
          environment: "disaster-recovery"

workflows:
  preview-disaster-recovery-from-feature-branch:
    jobs:
      - assume-role-disaster-recovery:
          context: api-assume-role-housing-disaster-recovery-context
          filters:
             branches:
               ignore: main
      - preview-terraform-disaster-recovery-changes:
          requires:
            - assume-role-disaster-recovery
          filters:
            branches:
              ignore: main
  terraform-apply-disaster-recovery:
    jobs:
      - start-disaster-recovery-release:
          type: approval
          filters:
            branches:
              only: main
      - assume-role-disaster-recovery:
          context: api-assume-role-housing-disaster-recovery-context
          requires:
              - start-disaster-recovery-release
          filters:
             branches:
               only: main
      - preview-terraform-disaster-recovery-changes:
          requires:
            - assume-role-disaster-recovery
          filters:
            branches:
              only: main
      - permit-disaster-recovery-terraform-release:
          type: approval
          requires:
            - preview-terraform-disaster-recovery-changes
          filters:
            branches:
              only: main
      - terraform-init-and-apply-to-disaster-recovery:
          requires:
            - permit-disaster-recovery-terraform-release
          filters:
            branches:
              only: main
