version: 2.1

orbs:
  aws-cli: circleci/aws-cli@0.1.9
  aws_assume_role: lbh-hackit/aws_assume_role@0.1.0

executors:
  docker-python:
    docker:
      - image: circleci/python:3.7
  docker-terraform:
    docker:
      - image: "hashicorp/terraform:light"

references:
  workspace_root: &workspace_root "~"
  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

commands:
  assume-role-and-persist-workspace:
    description: "Assumes deployment role and persists credentials across jobs"
    parameters:
      aws-account:
        type: string
    steps:
      - checkout
      - aws_assume_role/assume_role:
          account: <<parameters.aws-account>>
          profile_name: default
          role: "LBH_Circle_CI_Deployment_Role"
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - .aws
  # Init then Plan is used for "Preview" - don't add any "apply" steps
  terraform-init-then-plan:
    description: "Initializes and applies terraform configuration"
    parameters:
      environment:
        type: string
    steps:
      - *attach_workspace
      - checkout
      - run:
          command: |
            cd ./<<parameters.environment>>/
            terraform get -update=true
            terraform init
          name: get and init
      - run:
      # PLEASE LEAVE THIS AS A PLAN, IF YOU WANT TO CHANGE IT THEN SPEAK TO HUMAIRAA FIRST. 
          name: plan
          command: |
            cd ./<<parameters.environment>>/
            terraform plan
  # Used for actual deployment of Terraform resources.
  terraform-init-then-apply:
    description: "Initializes and applies terraform configuration"
    parameters:
      environment:
        type: string
    steps:
      - *attach_workspace
      - checkout
      - run:
          command: |
            cd ./<<parameters.environment>>/
            terraform get -update=true
            terraform init
          name: get and init
      - run:
          name: apply
          command: |
            cd ./<<parameters.environment>>/
            terraform apply -auto-approve

jobs:
  # Auth:
  assume-role-disaster-recovery:
    executor: docker-python
    steps:
      - assume-role-and-persist-workspace:
          aws-account: $AWS_ACCOUNT_DISASTER_RECOVERY
  # Infrastructure changes preview:
  preview-terraform-production-changes:
    executor: docker-terraform
    steps:
      - terraform-init-then-plan:
          environment: "production"
  # Infrastructure deployment:
  terraform-init-and-apply-to-production:
    executor: docker-terraform
    steps:
      - terraform-init-then-plan:
          environment: "production"

workflows:
  check-and-deploy-disaster-recovery:
    jobs:
      - assume-role-disaster-recovery:
          context: api-assume-role-disaster-recovery-context
          filters:
             branches:
               only: dr-testing
      - preview-terraform-production-changes:
          requires:
            - assume-role-production
          filters:
            branches:
              only: dr-testing
      - permit-terraform-release:
          # This approval is needed to make assume role prod trigger
          # when we actually need it, otherwise the temp creds will expire
          type: approval
          requires:
            - preview-terraform-production-changes
          filters:
            branches:
              only: dr-testing
      - terraform-init-and-apply-to-production:
          requires:
            - permit-terraform-release
          filters:
            branches:
              only: dr-testing
