version: 2.1

orbs:
  aws-cli: circleci/aws-cli@0.1.9
  aws_assume_role: lbh-hackit/aws_assume_role@0.1.0

executors:
  docker-python:
    docker:
      - image: circleci/python:3.7
  docker-terraform:
    docker:
      - image: "hashicorp/terraform:light"

references:
  workspace_root: &workspace_root "~"
  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

commands:
  assume-role-and-persist-workspace:
    description: "Assumes deployment role and persists credentials across jobs"
    parameters:
      aws-account:
        type: string
    steps:
      - checkout
      - aws_assume_role/assume_role:
          account: <<parameters.aws-account>>
          profile_name: default
          role: "LBH_Circle_CI_Deployment_Role"
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - .aws
  terraform-init-then-plan:
    description: "Initializes and applies terraform configuration"
    parameters:
      environment:
        type: string
    steps:
      - *attach_workspace
      - checkout
      - run:
          name: init root-infrastructure
          command: |
            cd ./<<parameters.environment>>/
            terraform get -update=true
            terraform init
      - run:
          name: plan root-infrastructure
          command: |
            cd ./<<parameters.environment>>/
            terraform plan -destroy
      - run:
          name: init charges-infrastructure
          command: |
            cd ./hfs-nightly-charges/production/
            terraform get -update=true
            terraform init
      - run:
          name: plan
          command: |
            cd ./hfs-nightly-charges/production/
            terraform plan -destroy
  terraform-init-then-apply:
    description: "Initializes and applies terraform configuration"
    parameters:
      environment:
        type: string
    steps:
      - *attach_workspace
      - checkout
      - run:
          command: aws --version 
      - run:
          command: |
            cd ./hfs-nightly-charges/production/
            terraform get -update=true
            terraform init
          name: get and init
      - run:
          name: destroy charges
          command: |
            cd ./hfs-nightly-charges/production/
            terraform destroy -auto-approve
      - run:
          command: |
            cd ./<<parameters.environment>>/
            terraform get -update=true
            terraform init
          name: get and init
      - run:
          name: destroy shared
          command: |
            cd ./<<parameters.environment>>/
            terraform destroy -auto-approve

jobs:
  assume-role-disaster-recovery:
    executor: docker-python
    steps:
      - assume-role-and-persist-workspace:
          aws-account: $AWS_ACCOUNT_DISASTER_RECOVERY
  preview-terraform-disaster-recovery-changes:
    executor: docker-terraform
    steps:
      - terraform-init-then-plan:
          environment: "production"
  deploy-to-disaster-recovery:
    executor: docker-terraform
    steps:
      - terraform-init-then-apply:
          environment: "production"

workflows:
  terraform-apply-disaster-recovery:
    jobs:
      - assume-role-disaster-recovery:
          context: api-assume-role-disaster-recovery-context
          filters:
             branches:
               only: disaster-recovery-branch
      - preview-terraform-disaster-recovery-changes:
          requires:
            - assume-role-disaster-recovery
          filters:
            branches:
              only: disaster-recovery-branch
      - permit-disaster-recovery-deployment:
          type: approval
          requires:
            - preview-terraform-disaster-recovery-changes
          filters:
            branches:
              only: disaster-recovery-branch
      - deploy-to-disaster-recovery:
          requires:
            - permit-disaster-recovery-deployment
          filters:
            branches:
              only: disaster-recovery-branch
